### ISSUE TITLE
Error - Send Expects Scriptable Object

### ISSUE THREAD

**Issue by Iowastater** [industrial-data/predictor-explainer#3]
Got teh error message below when trying to run the add-in on the Fermentation-Batch-Process file, using these inputs to the dialog box
![image](https://user-images.githubusercontent.com/7769312/206570485-f42e69d9-0952-4e48-8f6e-a1e98595eea2.png)

![image](https://user-images.githubusercontent.com/7769312/206569465-f2c0119d-2fbe-4436-adc2-e1cd55c6570e.png)

Running on -
JMP® Pro  17.0.0 (613300)  Early Adopter Edition 9
Administrator:  For Beta Testing Purposes Only
Organization:  Early Adopter Edition 9
Microsoft Windows 11 Enterprise (10.0.22000.0)

**Comment by franktoffel** [comment]
Would you please try downloading the latest version? V.22.11

This was a bug that should have been fixed with that release.

Does the distillation column example work?

**Comment by Iowastater** [comment]
Success!  Brilliant!  The add-in worked perfectly on the Fermentation data after updating to v22.11.

Very much looking forward to applying Predictor/Explainer on some of the longitudinal industrial data sets I’m currently working on.

  *   Predicting Mineral Buildup in Power Plant Cooling Lakes
  *   Explaining Mine Yield using Chemical Additives

There is so much information here, I am quite interested to learn more.  For example, I understand t-SNE, and therefore the concept of UMAP.  But how do you envision the UMAP values being used?  How do the row indexes relate to the initial data table?


Thank you,
Paul Prew

Paul Prew – Statistician
651-795-5942
F7503-A, 655 Lone Oak Dr., Eagan, MN 55121-1560



***@***.***
